#Splunk Connect for Syslog (SC4S) by Splunk, Inc.
#
#To the extent possible under law, the person who associated CC0 with
#Splunk Connect for Syslog (SC4S) has waived all copyright and related or neighboring rights
#to Splunk Connect for Syslog (SC4S).
#
#You should have received a copy of the CC0 legalcode along with this
#work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
version: 2.1

test: &test
  steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Setup for testing
        command: |
          pip install -r tests/requirements.txt
          mkdir test-results
    - run:
        name: Version
        command: |
          VERSION=$(./semtag getcurrent)
          echo $VERSION
          echo ${VERSION} >package/VERSION
    - run:
        name: test
        command: |
          docker-compose -f tests/docker-compose-ci.yml build 
          docker-compose -f tests/docker-compose-ci.yml up --abort-on-container-exit
        no_output_timeout: 1h
    - run:
        name: collect results
        when: always
        command: |
          docker container create --name dummy \
                              -v tests_results:/work/test-results \
                              registry.access.redhat.com/ubi7/ubi
          docker cp dummy:/work/test-results/test.xml test-results/
    - store_artifacts:
        path: test-results
        destination: test-results
    - store_test_results:
        path: test-results

tag: &tag
  steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
          - "7c:e9:cc:8d:8e:4d:9c:17:1d:e3:96:23:ce:bd:a4:c3"
    - checkout
    - run:
        name: TAG
        command: |
          ./semtag ${SEMTAG}

jobs:
  test-sc4s-3-25-1-splunk-8-0:
    docker:
      - image: circleci/python:3.7
    environment:
      SYSLOG: "syslog-ng-3.25.1"
      SPLUNK: "8.0"
    <<: *test
  test-sc4s-master-splunk-8-0:
    docker:
      - image: circleci/python:3.7
    environment:
      SYSLOG: "master"
      SPLUNK: "8.0"
    <<: *test
  test-sc4s-3-25-1-splunk-7-3:
    docker:
      - image: circleci/python:3.7
    environment:
      SYSLOG: "syslog-ng-3.25.1"
      SPLUNK: "7.3"
    <<: *test
  test-sc4s-3-25-1-splunk-7-2:
    docker:
      - image: circleci/python:3.7
    environment:
      SYSLOG: "syslog-ng-3.25.1"
      SPLUNK: "7.2"
    <<: *test

  tag-alpha:
    docker:
      - image: circleci/python:3.7
    environment:
      SEMTAG: "alpha"
    <<: *tag
  tag-beta:
    docker:
      - image: circleci/python:3.7
    environment:
      SEMTAG: "beta"
    <<: *tag
  tag-candidate:
    docker:
      - image: circleci/python:3.7
    environment:
      SEMTAG: "candidate"
    <<: *tag
  tag-final-major:
    docker:
      - image: circleci/python:3.7
    environment:
      SEMTAG: "final -s major"
    <<: *tag
  tag-final-minor:
    docker:
      - image: circleci/python:3.7
    environment:
      SEMTAG: "final -s minor"
    <<: *tag
  tag-final-patch:
    docker:
      - image: circleci/python:3.7
    environment:
      SEMTAG: "final -s patch"
    <<: *tag

  publish:
    docker:
      - image: circleci/python:3.7
    environment:
      SYSLOG: "syslog-ng-3.25.1"
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Docker Login
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build SC4S
          command: |
            if [ -n "${CIRCLE_TAG}" ]; then VERSION=${CIRCLE_TAG}; else VERSION="$(./semtag getcurrent)"; fi
            echo ${VERSION} >package/VERSION
            echo ${CIRCLE_SHA1}=${VERSION}
            docker build --build-arg BRANCH=${SYSLOG} package -t splunk/scs:${CIRCLE_SHA1}
            docker tag splunk/scs:${CIRCLE_SHA1} splunk/scs:${VERSION}
            docker tag splunk/scs:${CIRCLE_SHA1} splunk/scs:${CIRCLE_SHA1:0:7}
            docker push splunk/scs:${CIRCLE_SHA1}
            docker push splunk/scs:${VERSION}
            docker push splunk/scs:${CIRCLE_SHA1:0:7}

      #- go/install
      # - run:
      #     name: "Publish edge on GitHub"
      #     command: |
      #       PATH=$PATH:/usr/local/go/bin
      #       go get -v -u github.com/tcnksm/ghr
      #       if [ -n "${CIRCLE_TAG}" ]; then VERSION=${CIRCLE_TAG}; else VERSION="${DOCKER_TAG}"; fi
      #       PACKAGE=$(ls /tmp/workspace/build/package/splunkbase/*)
      #       [ "$(./semtag getfinal)" != "${CIRCLE_TAG}" ] && ISPRE="-prerelease" || ISPRE=""
      #       $HOME/go/bin/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${ISPRE} -delete ${VERSION} $PACKAGE

#     - run:
#         name: Build SC4S
#         command: |
#           echo $SEMVER_VERSION >package/VERSION
#           if [ -n "${CIRCLE_TAG}" ]; then VERSION=${CIRCLE_TAG}; else VERSION="${DOCKER_TAG}"; fi
#           docker build --build-arg BRANCH=${SYSLOG} package \
#             -t splunk/scs:${VERSION}
#     - run:
#         name: Docker Save
#         command: |
#           mkdir -p /tmp/workspace/
#           if [ -n "${CIRCLE_TAG}" ]; then VERSION=${CIRCLE_TAG}; else VERSION="${DOCKER_TAG}"; fi
#           docker save splunk/scs:${VERSION} | gzip -c > /tmp/workspace/oci_container.tar.gz
#     - run:
#         name: BYOE Config
#         command: |
#           tar rvf /tmp/workspace/baremetal.tar -C package/etc .
#           tar rvf /tmp/workspace/baremetal.tar -C package/sbin entrypoint.sh
#     - docker/push:
#         image: splunk/scs
#         tag: $DOCKER_TAG
#     - go/install
#     - run:
#         name: "Publish edge on GitHub"
#         command: |
#           PATH=$PATH:/usr/local/go/bin
#           go get -v -u github.com/tcnksm/ghr
#           if [ -n "${CIRCLE_TAG}" ]; then VERSION=${CIRCLE_TAG}; else VERSION="${DOCKER_TAG}"; fi
#           $HOME/go/bin/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${GHR_FLAGS} -delete ${VERSION} /tmp/workspace/

#     - store_artifacts:
#         path: /tmp/workspace/

# publish-edge:
#   docker:
#     - image: circleci/python:3.7
#   environment:
#     SYSLOG: "syslog-ng-3.25.1"
#     SPLUNK: "8.0"
#     DOCKER_TAG: edge
#     GHR_FLAGS: -prerelease
#   <<: *publish
# publish-latest:
#   docker:
#     - image: circleci/python:3.7
#   environment:
#     SYSLOG: "syslog-ng-3.25.1"
#     SPLUNK: "8.0"
#     DOCKER_TAG: latest
#   <<: *publish
# publish-tag:
#   docker:
#     - image: circleci/python:3.7
#   environment:
#     SYSLOG: "3.25.1"
#     SPLUNK: "8.0"
#   <<: *publish

workflows:
  version: 2
  build_test:
    jobs:
      - test-sc4s-3-25-1-splunk-8-0:
          filters:
            branches:
              only: /.*/
      - test-sc4s-master-splunk-8-0:
          filters:
            branches:
              only: /.*/
      - test-sc4s-3-25-1-splunk-7-3:
          filters:
            branches:
              only: /.*/
      - test-sc4s-3-25-1-splunk-7-2:
          filters:
            branches:
              only: /.*/
      - approval-tag-alpha:
          type: approval
          filters:
            branches:
              only: develop
      - tag-alpha:
          requires:
            - approval-tag-alpha
      - approval-tag-beta:
          requires:
            - tag-alpha
          type: approval
          filters:
            branches:
              only: develop
      - tag-beta:
          requires:
            - approval-tag-beta
  publish:
    jobs:
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d*\.\d*\.\d*.*$/
      # - publish-pre-gh-edge:
      #     type: approval
      #     requires:
      #       - test-sc4s-3-25-1-splunk-8-0
      #     filters:
      #       branches:
      #         only:
      #           - develop
      # - publish-edge:
      #     requires:
      #       - publish-pre-gh-edge
      # - publish-pre-gh-latest:
      #     type: approval
      #     requires:
      #       - test-sc4s-3-25-1-splunk-8-0
      #     filters:
      #       branches:
      #         only:
      #           - master
      # - publish-latest:
      #     requires:
      #       - publish-pre-gh-latest
      # - publish-pre-gh-tag:
      #     type: approval
      #     requires:
      #       - test-sc4s-3-25-1-splunk-8-0
      #     filters:
      #       tags:
      #         only: /^\d*\.\d*\.\d*.*$/
      #       branches:
      #         ignore: /.*/
      # - publish-tag:
      #     requires:
      #       - publish-pre-gh-tag
