    version: 2
    jobs:
      build:
        environment:
          IMAGE_NAME: rfaircloth/scs
        docker:
          - image: circleci/buildpack-deps:stretch
        steps:
          - checkout
          - run: git submodule sync
          - run: git submodule update --init --recursive
          - setup_remote_docker:
              docker_layer_caching: true
          - run:
              name: Build Docker image
              command: pushd package; docker build -f Dockerfile -t $IMAGE_NAME:build .

    workflows:
      version: 2
      build-publish:
        jobs:
          - build:
              filters:
                branches:
                  only:
                    - master
                    - develop