    version: 2
    jobs:
      build:
        environment:
          IMAGE_NAME: rfaircloth/scs
        docker:
          - image: circleci/buildpack-deps:stretch
        steps:
          - checkout
          - setup_remote_docker
          - run:
              name: Build Docker image
              command: docker build -f package/Dockerfile -t $IMAGE_NAME:latest .
    workflows:
      version: 2
      build-publish:
        jobs:
          - build:
              filters:
                branches:
                  only:
                    - master
                    - develop