#Splunk Connect for Syslog (SC4S) by Splunk, Inc.
#
#To the extent possible under law, the person who associated CC0 with
#Splunk Connect for Syslog (SC4S) has waived all copyright and related or neighboring rights
#to Splunk Connect for Syslog (SC4S).
#
#You should have received a copy of the CC0 legalcode along with this
#work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
version: 2.1

build-sc4s: &build-sc4s
  steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Docker Login
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker login -u $GITHUB_USER -p $GITHUB_TOKEN docker.pkg.github.com
    - run:
        name: Build SC4S
        command: |
          docker build --build-arg BRANCH=${SYSLOG} package \
            -t docker.pkg.github.com/splunk/splunk-connect-for-syslog/stg-splunk-connect-for-syslog:sc4s-${SYSLOG}-<< pipeline.id >>
    - run:
        name: Push SC4S
        command: |
          docker push \
            docker.pkg.github.com/splunk/splunk-connect-for-syslog/stg-splunk-connect-for-syslog:sc4s-${SYSLOG}-<< pipeline.id >>

build-splunk: &build-splunk
  steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Docker Login
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker login -u $GITHUB_USER -p $GITHUB_TOKEN docker.pkg.github.com
    - run:
        name: Build Splunk
        command: |
          docker build --build-arg SPLUNK_VERSION=${SPLUNK} splunk \
            -t docker.pkg.github.com/splunk/splunk-connect-for-syslog/stg-splunk-connect-for-syslog:splunk-${SYSLOG}-<< pipeline.id >>
    - run:
        name: Push Splunk
        command: |
          docker push \
            docker.pkg.github.com/splunk/splunk-connect-for-syslog/stg-splunk-connect-for-syslog:splunk-${SYSLOG}-<< pipeline.id >>


test: &test
  steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Docker Login
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker login -u $GITHUB_USER -p $GITHUB_TOKEN docker.pkg.github.com
    - run:
        name: Setup for testing
        command: |
          pip -r tests/requirements.txt
    - run:
        name: test
        command: |
          pytest --splunk_type=docker --splunk_password=${SPLUNK_PASSWORD}
        env:
          IMAGE_SC4S: docker.pkg.github.com/splunk/splunk-connect-for-syslog/stg-splunk-connect-for-syslog:sc4s-${SYSLOG}-<< pipeline.id >>
          IMAGE_SPLUNK: docker.pkg.github.com/splunk/splunk-connect-for-syslog/stg-splunk-connect-for-syslog:splunk-${SYSLOG}-<< pipeline.id >>


orbs:
  docker: circleci/docker@0.5.20
  go: circleci/go@0.2.0
  snyk: snyk/snyk@0.0.8
  versioning: kollex/versioning@1.0.0


jobs:
#JOB SC4S
  build-sc4s-3-25-1:
    docker:
      - image: circleci/buildpack-deps:18.04
    environment:
      SYSLOG: '3.25.1'
    <<: *build-sc4s
  build-sc4s-master:
    docker:
      - image: circleci/buildpack-deps:18.04
    environment:
      SYSLOG: 'master'
    <<: *build-sc4s
#JOB SPLUNK
  build-splunk-7-2:
    docker:
      - image: circleci/buildpack-deps:18.04
    environment:
      SPLUNK: '7.2'
    <<: *build-splunk
  build-splunk-7-3:
    docker:
      - image: circleci/buildpack-deps:18.04
    environment:
      SPLUNK: '7.3'
    <<: *build-splunk
  build-splunk-8-0:
    docker:
      - image: circleci/buildpack-deps:18.04
    environment:
      SPLUNK: '8.0'
    <<: *build-splunk
  test-sc4s-3-25-1-splunk-8-0:
    docker:
      - image: circleci/buildpack-deps:18.04
    environment:
      SYSLOG: '3.25.1'
      SPLUNK: '8.0'
    <<: *test
  test-sc4s-master-splunk-8-0:
    docker:
      - image: circleci/buildpack-deps:18.04
    environment:
      SYSLOG: 'master'
      SPLUNK: '8.0'
    <<: *test
  test-sc4s-3-25-1-splunk-7-3:
    docker:
      - image: circleci/buildpack-deps:18.04
    environment:
      SYSLOG: '3.25.1'
      SPLUNK: '7.3'
    <<: *test
  test-sc4s-3-25-1-splunk-7-2:
    docker:
      - image: circleci/python:3.7
    environment:
      SYSLOG: '3.25.1'
      SPLUNK: '7-2'
    <<: *test

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-sc4s-3-25-1
      - build-sc4s-master
      - build-splunk-7-2
      - build-splunk-7-3
      - build-splunk-8-0
      - test-sc4s-3-25-1-splunk-8-0:
          requires:
            - build-sc4s-3-25-1
            - build-splunk-8-0
      - test-sc4s-master-splunk-8-0:
          requires:
            - build-sc4s-master
            - build-splunk-8-0
      - test-sc4s-3-25-1-splunk-7-3:
          requires:
            - build-sc4s-3-25-1
            - build-splunk-7-3
      - test-sc4s-3-25-1-splunk-7-2:
          requires:
            - build-sc4s-3-25-1
            - build-splunk-7-2
