#Splunk Connect for Syslog (SC4S) by Splunk, Inc.
#
#To the extent possible under law, the person who associated CC0 with
#Splunk Connect for Syslog (SC4S) has waived all copyright and related or neighboring rights
#to Splunk Connect for Syslog (SC4S).
#
#You should have received a copy of the CC0 legalcode along with this
#work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
version: 2.1

build-sc4s: &build-sc4s
  steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Docker Login
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker login -u $GITHUB_USER -p $GITHUB_TOKEN docker.pkg.github.com
    - semver-orb/export-tag
    - run:
        name: Build SC4S
        command: |
          echo $SEMVER_VERSION
          echo $SEMVER_VERSION >package/VERSION
          docker build --build-arg BRANCH=${SYSLOG} package \
            -t docker.pkg.github.com/splunk/splunk-connect-for-syslog/stg-splunk-connect-for-syslog:sc4s-${SYSLOG}-<< pipeline.id >>
    - run:
        name: Push SC4S
        command: |
          docker push \
            docker.pkg.github.com/splunk/splunk-connect-for-syslog/stg-splunk-connect-for-syslog:sc4s-${SYSLOG}-<< pipeline.id >>

    - run:
        name: Docker Save
        command: |
          mkdir -p /tmp/workspace-${SYSLOG}
          docker save $REGISTRY/$CI_IMAGE:$CIRCLE_SHA1 | gzip -c > /tmp/workspace-${SYSLOG}/oci_container.tar.gz

    - persist_to_workspace:
        root: /tmp
        paths:
          - workspace-${SYSLOG}

build-splunk: &build-splunk
  steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Docker Login
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker login -u $GITHUB_USER -p $GITHUB_TOKEN docker.pkg.github.com
    - run:
        name: Build Splunk
        command: |
          docker build --build-arg SPLUNK_VERSION=${SPLUNK} splunk \
            -t docker.pkg.github.com/splunk/splunk-connect-for-syslog/stg-splunk-connect-for-syslog:splunk-${SPLUNK}-<< pipeline.id >>
    - run:
        name: Push Splunk
        command: |
          docker push \
            docker.pkg.github.com/splunk/splunk-connect-for-syslog/stg-splunk-connect-for-syslog:splunk-${SPLUNK}-<< pipeline.id >>



test: &test
  steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Docker Login
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker login -u $GITHUB_USER -p $GITHUB_TOKEN docker.pkg.github.com
    - run:
        name: Setup for testing
        command: |
          pip install -r tests/requirements.txt
          mkdir test-results
    - run:
        name: test
        command: |
          docker-compose -f tests/docker-compose.yml pull
          docker-compose -f tests/docker-compose.yml up --abort-on-container-exit
          docker cp results:/* test-results/
        no_output_timeout: 1h
    - store_artifacts:
        path: test-results
        destination: apptest-${SYSLOG}-${SPLUNK}
    - store_test_results:
        path: test-results


orbs:
  docker: circleci/docker@0.5.20
  go: circleci/go@0.2.0
  snyk: snyk/snyk@0.0.8
  versioning: kollex/versioning@1.0.0
  semver-orb: tv2norge/semver-orb@0.0.1

jobs:
  build-byoe:
    docker:
      - image: circleci/buildpack-deps:18.04
    environment:
      SYSLOG: '3.25.1'
    steps:
      - checkout
      - run:
          name: BYOE Config
          command: |
            mkdir -p /tmp/workspace-byoe/
            tar rvf /tmp/workspace-byoe/baremetal.tar -C package/etc .
            tar rvf /tmp/workspace-byoe/baremetal.tar -C package/sbin entrypoint.sh
      - persist_to_workspace:
          root: /tmp
          paths:
            - workspace-byoe

  build-tests:
    docker:
      - image: circleci/buildpack-deps:18.04
    environment:
      SYSLOG: '3.25.1'
    steps:
        - checkout
        - setup_remote_docker:
            docker_layer_caching: true
        - run:
            name: Docker Login
            command: |
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker login -u $GITHUB_USER -p $GITHUB_TOKEN docker.pkg.github.com
        - run:
            name: Build Splunk
            command: |
              docker build tests \
                -t docker.pkg.github.com/splunk/splunk-connect-for-syslog/stg-splunk-connect-for-syslog:tests-<< pipeline.id >>
        - run:
            name: Push Splunk
            command: |
              docker push \
                docker.pkg.github.com/splunk/splunk-connect-for-syslog/stg-splunk-connect-for-syslog:tests-<< pipeline.id >>

#JOB SC4S
  build-sc4s-3-25-1:
    docker:
      - image: circleci/buildpack-deps:18.04
    environment:
      SYSLOG: '3.25.1'
    <<: *build-sc4s
  build-sc4s-master:
    docker:
      - image: circleci/buildpack-deps:18.04
    environment:
      SYSLOG: 'master'
    <<: *build-sc4s
#JOB SPLUNK
  build-splunk-7-2:
    docker:
      - image: circleci/buildpack-deps:18.04
    environment:
      SPLUNK: '7.2'
    <<: *build-splunk
  build-splunk-7-3:
    docker:
      - image: circleci/buildpack-deps:18.04
    environment:
      SPLUNK: '7.3'
    <<: *build-splunk
  build-splunk-8-0:
    docker:
      - image: circleci/buildpack-deps:18.04
    environment:
      SPLUNK: '8.0'
    <<: *build-splunk
  test-sc4s-3-25-1-splunk-8-0:
    docker:
      - image: circleci/python:3.7
    environment:
      SYSLOG: '3.25.1'
      SPLUNK: '8.0'
    <<: *test
  test-sc4s-master-splunk-8-0:
    docker:
      - image: circleci/python:3.7
    environment:
      SYSLOG: 'master'
      SPLUNK: '8.0'
    <<: *test
  test-sc4s-3-25-1-splunk-7-3:
    docker:
      - image: circleci/python:3.7
    environment:
      SYSLOG: '3.25.1'
      SPLUNK: '7.3'
    <<: *test
  test-sc4s-3-25-1-splunk-7-2:

    docker:
      - image: circleci/python:3.7
    environment:
      SYSLOG: '3.25.1'
      SPLUNK: '7-2'
    <<: *test

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-tests
      - build-sc4s-3-25-1
      - build-sc4s-master
      - build-splunk-7-2
      - build-splunk-7-3
      - build-splunk-8-0
      - test-sc4s-3-25-1-splunk-8-0:
          requires:
            - build-sc4s-3-25-1
            - build-splunk-8-0
            - build-tests
      - test-sc4s-master-splunk-8-0:
          requires:
            - build-sc4s-master
            - build-splunk-8-0
            - build-tests
      - test-sc4s-3-25-1-splunk-7-3:
          requires:
            - build-sc4s-3-25-1
            - build-splunk-7-3
            - build-tests
      - test-sc4s-3-25-1-splunk-7-2:
          requires:
            - build-sc4s-3-25-1
            - build-splunk-7-2
            - build-tests
