name: Test Matrix

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        syslog-version: [3.25.1]
        #splunk-version: [7.2,7.3,8.0,edge]
        splunk-version: [8.0]

    steps:
    - name: Checkout private tools
      uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ secrets.GitHub_User }}
        password: ${{ secrets.GitHub_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
    - name: Build
      run: |
        docker-compose -f tests/docker-compose.yml build
    - name: Build
      run: |
        docker-compose -f tests/docker-compose.yml up -d
        sleep 80
        docker-compose -f tests/docker-compose.yml logs
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v \
          --rootdir=$(pwd) \
          --splunk_type=external \
          --splunk_host=127.0.0.1 \
          --splunk_port=8089 \
          --splunk_version=${{ matrix.splunk-version }} \
          --splunk_password=${{ secrets.GitHub_PAT }}
      env:
        SPLUNKBASE_PASSWORD: ${{ secrets.SPLUNKBASE_PASSWORD }}
        SPLUNK_HEC_TOKEN: ${{ secrets.SPLUNK_HEC_TOKEN }}
        SPLUNK_START_ARGS:  ${{ secrets.SPLUNK_START_ARGS }}
