name: Test Matrix

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        syslog-version: [3.25.1,master]

    steps:
    - name: Checkout private tools
      uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ secrets.GitHub_User }}
        password: ${{ secrets.GitHub_PAT }}

    - name: Build for ${{ matrix.version }}
      run: |
        docker build --build-arg BRANCH=${{ matrix.version }} package \
          -t docker.pkg.github.com/${GITHUB_REPOSITORY}/stg-splunk-connect-for-syslog:sc4s-${{ matrix.version }}-${{ github.sha }}

